{% set name = "hyp3_sdk" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a408976d7a9449beae93221d1bcdeabb61273bf0d98434ef154046eef2fd050

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >=3.8
    - python-dateutil
    - requests
    - tqdm
    - urllib3

test:
  imports:
    - hyp3_sdk
    - hyp3_sdk.asf_search
    - hyp3_sdk.jobs
    - hyp3_sdk.hyp3
    - hyp3_sdk.util
    - hyp3_sdk.exceptions

about:
  home: https://github.com/ASFHyP3/hyp3-sdk
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A python wrapper around the HyP3 API

extra:
  recipe-maintainers:
    - jhkennedy
    - asjohnston-asf
    - jlrine2
