{% set name = "hyp3_sdk" %}
{% set version = "1.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ce85b0a86630d498bae183ad47d23e6185c184d7462583c89745fa5fa70cabf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61
    - setuptools_scm >=6.2
    - python-build
  run:
    - python >=3.8
    - python-dateutil
    - requests
    - tqdm
    - urllib3

test:
  imports:
    - hyp3_sdk
    - hyp3_sdk.jobs
    - hyp3_sdk.hyp3
    - hyp3_sdk.util
    - hyp3_sdk.exceptions

about:
  home: https://github.com/ASFHyP3/hyp3-sdk
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A python wrapper around the HyP3 API

extra:
  recipe-maintainers:
    - jhkennedy
    - asjohnston-asf
    - jtherrmann
    - jacquelynsmale
